version: '3.2'
services:
  postgres:
    image: postgres:latest
    container_name: "postgres"
    environment:
      - POSTGRES_DB=graphql_demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT
    ports:
      - "5432:5432"